package dev.manojc.cleartaxsdk.models.transaction.exportdetails;

import java.util.Arrays;
import java.util.Optional;

import javax.validation.constraints.NotBlank;

import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

@JsonFormat(shape = JsonFormat.Shape.STRING)
public enum PortCode {
	@JsonProperty("Port")
	INABG1("INABG1"), // Alibag
	INACH1("INACH1"), // Achra
	INADA6("INADA6"), // Ahmedabad Adalaj
	INADI1("INADI1"), // Androth Island
	INAGI1("INAGI1"), // Agatti Island
	INAGR4("INAGR4"), // Agra
	INAGR5("INAGR5"), // FPO AGRA
	INAGR6("INAGR6"), // Agra
	INAGTB("INAGTB"), // Agartala
	INAGX4("INAGX4"), // Agatti Island
	INAHD6("INAHD6"), // ICD SANAND
	INAIG6("INAIG6"), // GE PVT. LTD.
	INAII6("INAII6"), // M/S IGATE GS LTD.
	INAIK6("INAIK6"), // IBRAHIMPURICD KHURJA
	INAIR6("INAIR6"), // SP PVT. LTD.
	INAJE6("INAJE6"), // WLSPUN ANJAR SEZ
	INAJJ6("INAJJ6"), // Arakkonam Melpakkam
	INAJL4("INAJL4"), // Aizawl
	INAJM6("INAJM6"), // MUNDRA PORT SEZ
	INAKB6("INAKB6"), // BIACPL SEZ
	INAKD4("INAKD4"), // Akola
	INAKP6("INAKP6"), // APIICL SEZ
	INAKR6("INAKR6"), // RPCIPL SEZ
	INAKV6("INAKV6"), // Ankleshwar ICD
	INALA1("INALA1"), // ALANG SBY
	INALF1("INALF1"), // Allepey
	INAMD4("INAMD4"), // Ahmedabad
	INAMD5("INAMD5"), // Ahmedabad
	INAMD6("INAMD6"), // Ahmedabad
	INAMG6("INAMG6"), // Amingaon (Gauhati)
	INAMI1("INAMI1"), // Amini Island
	INAMK6("INAMK6"), // KSITIL/SEZ/ALAPPUZHA
	INANG1("INANG1"), // Anijengo
	INANL1("INANL1"), // Arnala
	INAPI6("INAPI6"), // AAP-SEZ AHMEDABAD
	INAPL6("INAPL6"), // Dadri ACPL CFS
	INAPT6("INAPT6"), // Anaparti
	INARR6("INARR6"), // Aroor
	INASR2("INASR2"), // Amritsar Railway Stn
	INASR6("INASR6"), // Amritsar
	INATQ4("INATQ4"), // Amritsar
	INATQ6("INATQ6"), // Amritsar
	INATRB("INATRB"), // Attari Road
	INATT2("INATT2"), // Attari Railway Stat
	INAWM6("INAWM6"), // SEZ, SHENDRA
	INAWS6("INAWS6"), // SOMANI SEZ BHIWADI
	INAWW6("INAWW6"), // WIDL AEZ, AURANGABAD
	INAZK1("INAZK1"), // Azhikkal
	INBAG6("INBAG6"), // GEM&JEWEL-SEZ/ULWE
	INBAI6("INBAI6"), // IT/ITES-B-SEZ/ULWE
	INBAM6("INBAM6"), // MULTISERVCE-SEZ/ULWE
	INBAP6("INBAP6"), // MULTISERVICEDRONAGIR
	INBAT6("INBAT6"), // IT/ITES-C SEZ/UIWE
	INBAU6("INBAU6"), // IT/ITES-A-SEZ/ULWE
	INBAW6("INBAW6"), // ICD BAWAL
	INBBI4("INBBI4"), // Bhubaneswar
	INBBM6("INBBM6"), // Bari Brahamna ICD
	INBBP1("INBBP1"), // Bahabal Pur
	INBBS6("INBBS6"), // SEZ, OIIDC, BHUBANES
	INBCH6("INBCH6"), // HARI SEZ VARANASI
	INBCO6("INBCO6"), // EURO MULTIVISION SEZ
	INBCP6("INBCP6"), // PRITECH/SEZ/BANGLORE
	INBDB6("INBDB6"), // PRECIOUSCARGOCUSTOMS
	INBDG1("INBDG1"), // Badagara
	INBDH6("INBDH6"), // ICD BADOHI
	INBDI6("INBDI6"), // ICD BADDI,
	INBDM6("INBDM6"), // ICD, PANCHI, SONIPAT
	INBDQ1("INBDQ1"), // Vadodara
	INBDR1("INBDR1"), // Baindur
	INBED1("INBED1"), // Bedi
	INBEK4("INBEK4"), // Bareilly
	INBEP4("INBEP4"), // Bellary
	INBET1("INBET1"), // Betul
	INBEY1("INBEY1"), // Beypore
	INBFR6("INBFR6"), // M/S GRFL, ICD, BALLA
	INBGK6("INBGK6"), // Bhagat ki Kothi Jodh
	INBGMB("INBGMB"), // Baghmara
	INBGQ6("INBGQ6"), // QUEST SEZ BELGAUM
	INBGUB("INBGUB"), // Bairgania
	INBGW1("INBGW1"), // Bhagwa
	INBHC6("INBHC6"), // JUBILANT/SEZ/VILAYAT
	INBHD6("INBHD6"), // DAHEZ SEZ
	INBHJ4("INBHJ4"), // Bhuj
	INBHL6("INBHL6"), // Bhilwara
	INBHM1("INBHM1"), // Bheemunipatnam
	INBHO4("INBHO4"), // Bhopal
	INBHS6("INBHS6"), // STERLING BHARUCH
	INBHU1("INBHU1"), // Bhavanagar
	INBHU4("INBHU4"), // Bhavanagar
	INBKB4("INBKB4"), // Bikaner
	INBKR1("INBKR1"), // Belekeri
	INBKT1("INBKT1"), // Bankot
	INBLC6("INBLC6"), // CESSNA/SEZ/BANGALORE
	INBLE6("INBLE6"), // CONCOR ICD BALASORE
	INBLJ6("INBLJ6"), // Agra
	INBLK1("INBLK1"), // Belekeri
	INBLM1("INBLM1"), // Bilimora
	INBLP1("INBLP1"), // Belapur
	INBLR4("INBLR4"), // Bangalore
	INBLR5("INBLR5"), // Bangalore
	INBLR6("INBLR6"), // Bangalore
	INBLTB("INBLTB"), // Balet
	INBLV6("INBLV6"), // VTV/SEZ/BANGALORE
	INBMA6("INBMA6"), // APIIC PRAKASHAM
	INBMR2("INBMR2"), // Barmer Railway Stati
	INBNC6("INBNC6"), // KBITS SEZ BANGALORE
	INBND1("INBND1"), // Bandra
	INBNG6("INBNG6"), // MAHAGAON ICD, THANE
	INBNK6("INBNK6"), // KOLKATA IT PARK
	INBNP1("INBNP1"), // Bheemunipatnam
	INBNRB("INBNRB"), // Bhimnagar
	INBNT6("INBNT6"), // TCS
	INBNW6("INBNW6"), // WIPRO SEZ
	INBNX6("INBNX6"), // CANDOR ONE HTSPL,SEZ
	INBNYB("INBNYB"), // Berhni
	INBOK6("INBOK6"), // BORKHEDI ICD NAGPUR
	INBOLB("INBOLB"), // Bolanganj
	INBOM1("INBOM1"), // Mumbai (Ex Bombay)
	INBOM4("INBOM4"), // Mumbai (Ex Bombay)
	INBOM5("INBOM5"), // Mumbai (Ex Bombay)
	INBOM6("INBOM6"), // Mumbai(EPZ/SEZ)
	INBPL5("INBPL5"), // BHOPAL FPO
	INBPS5("INBPS5"), // APSO MUMBAI
	INBRAB("INBRAB"), // Barsora
	INBRC6("INBRC6"), // Baroda
	INBRH1("INBRH1"), // Broach
	INBRI6("INBRI6"), // RNBIPL SEZ BIKANER
	INBRL6("INBRL6"), // L & T/SEZ/VADODARA
	INBRM1("INBRM1"), // Borlai ¿ Mandla
	INBRS6("INBRS6"), // S E & C/SEZ/WAGHODIA
	INBRY1("INBRY1"), // Borya
	INBSAB("INBSAB"), // Banbasa
	INBSB6("INBSB6"), // Varanasi
	INBSL6("INBSL6"), // Bhusaval ICD
	INBSN1("INBSN1"), // Bassein
	INBSR1("INBSR1"), // Bulsar
	INBSW6("INBSW6"), // AFS KAPASHERA
	INBTK1("INBTK1"), // Bhatkal
	INBTMB("INBTMB"), // Bhithamore(Sursnad)
	INBTR1("INBTR1"), // Bitra Island
	INBUD1("INBUD1"), // Budge-Budge
	INBUL6("INBUL6"), // AN FTWZ BULANDSHAHR
	INBUP4("INBUP4"), // Bhatinda
	INBUP6("INBUP6"), // Bhatinda
	INBVC6("INBVC6"), // CONCR-ICD/BALLABGARH
	INBWD6("INBWD6"), // Bhiwadi
	INBWN1("INBWN1"), // Bhiwandi
	INBXR6("INBXR6"), // DLF LTD., SEZ
	INBYT1("INBYT1"), // Beyt
	INCAG6("INCAG6"), // TATA STEEL SEZGANJAM
	INCAM1("INCAM1"), // Cambay
	INCAP1("INCAP1"), // Calingapatam
	INCAR1("INCAR1"), // Carijam
	INCAS6("INCAS6"), // SAPL SEZ/ GANJAM
	INCBC6("INCBC6"), // CHIPL SEZ/ COIMBATOR
	INCBD4("INCBD4"), // Car Nicobar
	INCBDB("INCBDB"), // Changrabandh
	INCBE6("INCBE6"), // COIMBATORE
	INCBL1("INCBL1"), // Chandbali
	INCBS6("INCBS6"), // SE&C COIMBATORE
	INCCH6("INCCH6"), // Chinchwad ICD
	INCCI6("INCCI6"), // WIPRO SEZ HINJEWADI
	INCCJ1("INCCJ1"), // Kozhikode (ex Calicu
	INCCJ4("INCCJ4"), // Kozhikode (ex Calicu
	INCCP6("INCCP6"), // PEPPL SEZ, CHINCHWAD
	INCCQ6("INCCQ6"), // M/S QB PARK LTD.
	INCCT6("INCCT6"), // KINFRAFP SEZ
	INCCU1("INCCU1"), // Calcutta
	INCCU4("INCCU4"), // Calcutta
	INCCU5("INCCU5"), // Calcutta
	INCCW6("INCCW6"), // WIPRO LTD.
	INCDC6("INCDC6"), // RGT PARK (PHASE-II)
	INCDD6("INCDD6"), // RGT PARK (PHASE-I)
	INCDL1("INCDL1"), // Cuddalore
	INCDP1("INCDP1"), // Coondapur (Ganguly)
	INCDP4("INCDP4"), // Cuddapah
	INCDP6("INCDP6"), // M/S APIIC LTD SEZ.
	INCDQ6("INCDQ6"), // QUARKCITY/SEZ/MOHALI
	INCDR6("INCDR6"), // SUN PHARMACEUTICALS
	INCEC6("INCEC6"), // L&T AE IT SEZ PVT.
	INCGA6("INCGA6"), // MWCD APARELS CHENGPA
	INCGE6("INCGE6"), // ETA TECH. PVT. LTD.
	INCGI6("INCGI6"), // MWCD SEZ CHENGALPATU
	INCGL6("INCGL6"), // MWCD AUTO ANCILARIES
	INCHE6("INCHE6"), // Tiruppur-Chettipalay
	INCHJ6("INCHJ6"), // ICD WARDHA
	INCHL1("INCHL1"), // Colachel
	INCHMB("INCHMB"), // Chamurchi
	INCHN6("INCHN6"), // Vadodara Chhani CFS
	INCHPB("INCHPB"), // Champai
	INCHR1("INCHR1"), // Chapora
	INCJA6("INCJA6"), // L&T AE IT SEZ
	INCJB4("INCJB4"), // Coimbatore
	INCJB6("INCJB6"), // Coimbatore
	INCJC6("INCJC6"), // NCTL (ENGG.) SEZ/ KA
	INCJD6("INCJD6"), // DLF INFOCITY DEV.
	INCJE6("INCJE6"), // ECTN KANCHEEPURAM
	INCJF6("INCJF6"), // FTIL SRIPERUMBUDUR
	INCJH6("INCJH6"), // ICD WARDHA
	INCJI6("INCJI6"), // ETL IS LTD.
	INCJJ6("INCJJ6"), // J M FTZ/SEZ/MANNUR
	INCJN6("INCJN6"), // NIPL SEZ SRIPERUMBUD
	INCJO6("INCJO6"), // SIPCOT ORAGADAM SRIP
	INCJS6("INCJS6"), // SIPCOT SRIPERUMBUDUR
	INCLK6("INCLK6"), // KSITIL/SEZ/KOZHIKODE
	INCLU6("INCLU6"), // ULCCS/SEZ/KOZHIKODE
	INCLX6("INCLX6"), // Chirala
	INCMB1("INCMB1"), // Cambay
	INCML6("INCML6"), // KATHUWAS ICD ALWAR
	INCNB1("INCNB1"), // Car-Nicobar
	INCNC6("INCNC6"), // NCT PVT. LTD. SEZ
	INCNN1("INCNN1"), // Cannanore
	INCOA6("INCOA6"), // KAKINADA SEZ KAKINAD
	INCOH4("INCOH4"), // Cooch Behar
	INCOK1("INCOK1"), // Cochin
	INCOK4("INCOK4"), // Cochin
	INCOK6("INCOK6"), // Cochin(EPZ/SEZ)
	INCOL1("INCOL1"), // Colochel
	INCOO1("INCOO1"), // Coondapur (Ganguly)
	INCOP6("INCOP6"), // PARRY SEZ KAKINADA
	INCPC6("INCPC6"), // Kanpur Chakeri
	INCPL6("INCPL6"), // Dadri CGML
	INCPR6("INCPR6"), // ICD CHAWAPAYAL
	INCRL6("INCRL6"), // RGA SEZ CHIKKANKANNE
	INCRN1("INCRN1"), // Cornwallis
	INCRW6("INCRW6"), // WIPRO/SEZ/BANGALORE
	INCRXB("INCRXB"), // LOKSAN LCS
	INCSP6("INCSP6"), // SI PVT. LTD.
	INCSV6("INCSV6"), // SPVL SEZ COIMBATORE
	INCTI1("INCTI1"), // Chetlat Island
	INCUM1("INCUM1"), // Cutch Mandvi
	INDAE4("INDAE4"), // Daparizo
	INDAH1("INDAH1"), // Dahej
	INDAI4("INDAI4"), // Darjeeling
	INDAM1("INDAM1"), // Daman
	INDAM4("INDAM4"), // Daman
	INDAR6("INDAR6"), // ARTHA SEZ GR. NOIDA
	INDBD4("INDBD4"), // Dhanbad
	INDBS6("INDBS6"), // SANTA-SEZ/ViII-MUPPI
	INDDL6("INDDL6"), // PSWC ICD DHANDARIKAL
	INDEA6("INDEA6"), // AS PVT. LTD.
	INDED4("INDED4"), // Dehra Dun
	INDEF6("INDEF6"), // INFOSYS SEZ DADRI
	INDEG1("INDEG1"), // Deogad
	INDEH6("INDEH6"), // HCL TECH. LTD. DEV.
	INDEI6("INDEI6"), // IVR SEZ NOIDA
	INDEJ6("INDEJ6"), // JUBILANT SEZ NOIDA
	INDEL4("INDEL4"), // Delhi
	INDEL5("INDEL5"), // Delhi
	INDEM6("INDEM6"), // MOSERBAER/SEZ/NOIDA
	INDEN6("INDEN6"), // M/S NIIT TECH. LTD.
	INDEP4("INDEP4"), // Deparizo
	INDER6("INDER6"), // Dadri
	INDES6("INDES6"), // M/S SEAVIEW DEV. LTD
	INDET6("INDET6"), // UNITECH HITECH NOIDA
	INDEU6("INDEU6"), // UNITECHINFRA NOIDA
	INDEW6("INDEW6"), // M/S WIPRO LTD.
	INDGI6("INDGI6"), // GALLANT SEZ NOIDA
	INDGT6("INDGT6"), // GOLDEN SEZ NOIDA
	INDHA6("INDHA6"), // Indore-Dhannad
	INDHBB("INDHBB"), // Dhubri Steamerghat
	INDHLB("INDHLB"), // Dhalaighat
	INDHM4("INDHM4"), // Dharamsala
	INDHN1("INDHN1"), // Dahanu
	INDHP1("INDHP1"), // Dabhol Port
	INDHR1("INDHR1"), // Dholera
	INDHU1("INDHU1"), // Dahanu
	INDIB4("INDIB4"), // Dibrugarh
	INDID6("INDID6"), // SEZ, MIDC, NANDED
	INDIG1("INDIG1"), // Dighi Port
	INDIG6("INDIG6"), // Dighi (Pune)
	INDIT6("INDIT6"), // ANSAL IT/SEZ/NOIDA
	INDIU1("INDIU1"), // Diu
	INDIU4("INDIU4"), // Diu
	INDIV1("INDIV1"), // Div
	INDLAB("INDLAB"), // Dharchula
	INDLH6("INDLH6"), // APLLP SEZ BENGALURU
	INDLI2("INDLI2"), // Delhi Railway Statio
	INDLOB("INDLOB"), // BIRPARA LCS
	INDLUB("INDLUB"), // Dalu
	INDMA1("INDMA1"), // DHAMRA
	INDMRB("INDMRB"), // Demagir
	INDMT1("INDMT1"), // Dharamtar
	INDMU4("INDMU4"), // Dimapur
	INDPC4("INDPC4"), // DPC BKC Mumbai
	INDPR6("INDPR6"), // DAPPER
	INDRC6("INDRC6"), // RCIPL SEZ NOIDA
	INDRGB("INDRGB"), // Darranga
	INDRK1("INDRK1"), // Dwarka (Rupen)
	INDRL1("INDRL1"), // Dabolim
	INDRU6("INDRU6"), // Belgaum Desur
	INDSK1("INDSK1"), // Dhanu-shkodi
	INDSM6("INDSM6"), // SMRTPL SEZ NOIDA
	INDTW1("INDTW1"), // Dantiwara
	INDUR6("INDUR6"), // ICD Durgapur
	INDWA1("INDWA1"), // Dwarka
	INDWKB("INDWKB"), // Dawki
	INDWN6("INDWN6"), // ICD SAMALKHA PANIPAT
	INDWR6("INDWR6"), // INFOSYS SEZ HUBLI
	INENR1("INENR1"), // KAMARAJAR PORT LTD
	INERP6("INERP6"), // PUTHUVYPEEN SEZ
	INERV6("INERV6"), // VALLARPADOM SEZ
	INESH1("INESH1"), // Elphinstone Harbour
	INFBD6("INFBD6"), // ICD Faridabad
	INFBE6("INFBE6"), // ESPIRE SEZ FARIDABAD
	INFBM6("INFBM6"), // METRO SEZ GURGAON
	INFBP6("INFBP6"), // PERPETUAL FARIDABAD
	INFBRB("INFBRB"), // Fulbari LCS
	INFBS6("INFBS6"), // SELECTOSEZ FARIDABAD
	INFCH5("INFCH5"), // FPO(SEA) CHENNAI
	INFLT6("INFLT6"), // Falta(SEZ)
	INFMA6("INFMA6"), // APIICL MEDAK
	INFMH6("INFMH6"), // HGSEZL RANGA REDDY
	INFMJ6("INFMJ6"), // M/S J.T. SEZ, RANGAR
	INFMS6("INFMS6"), // M/S STARGAZE, SEZ
	INGAIB("INGAIB"), // Gauriphanta
	INGALB("INGALB"), // Galgalia
	INGAO6("INGAO6"), // OPGS POWER GUJARAT
	INGAS6("INGAS6"), // ANSAL SEZ GURGAON
	INGAU1("INGAU1"), // Gauhati (Panidi)
	INGAU2("INGAU2"), // Gauhati (Panidi)
	INGAU4("INGAU4"), // Gauhati (Panidi)
	INGAU5("INGAU5"), // FPO GUWAHATI
	INGAW2("INGAW2"), // Guwahati
	INGAY4("INGAY4"), // Gaya
	INGDL6("INGDL6"), // DLF CYBERCITY SEZ,
	INGDM6("INGDM6"), // MF PARK PVT. LTD.
	INGDP6("INGDP6"), // FLLPL SEZ THIRUVALUR
	INGED2("INGED2"), // Gede Railway Station
	INGGA1("INGGA1"), // Gogha
	INGGB6("INGGB6"), // SBPL SEZ GURGAON
	INGGC6("INGGC6"), // ORIENT SEZ GURGAON
	INGGD6("INGGD6"), // DLF LTD.
	INGGE6("INGGE6"), // AEPL SEZ GURGAON
	INGGF6("INGGF6"), // FRESH SEZ GURGAON
	INGGG6("INGGG6"), // GHI SEZ GURGAON
	INGGI6("INGGI6"), // GIL SEZ, GURGAON
	INGGL6("INGGL6"), // LUXOR SEZ GURGAON
	INGGM6("INGGM6"), // MIPPL SEZ GURGAON
	INGGN2("INGGN2"), // Gurgaon
	INGGO6("INGGO6"), // ORIENTCRAFT SEZ GGN
	INGGP6("INGGP6"), // SUNWISE SEZ GURGAON
	INGGS6("INGGS6"), // SUNCITY SEZ GURGAON
	INGGU6("INGGU6"), // URP LTD.
	INGGV1("INGGV1"), // GANGAVARAM PORT
	INGHA1("INGHA1"), // Ghogha
	INGHC6("INGHC6"), // ASF INSIGNIA SEZ
	INGHPB("INGHPB"), // Ghasuapara
	INGHR6("INGHR6"), // Garhi Harsaru Gurgao
	INGHWB("INGHWB"), // Gauhati Steamerghat
	INGID6("INGID6"), // MID PLTD SEZ GURGAON
	INGIN6("INGIN6"), // Gandhidham
	INGJIB("INGJIB"), // Gunji
	INGJXB("INGJXB"), // Ghojadanga
	INGKJ2("INGKJ2"), // Golakganj Railway St
	INGKJB("INGKJB"), // Golakganj LCS
	INGLY6("INGLY6"), // APIIC MAHABOOBNAGAR
	INGMI6("INGMI6"), // MID PVT LTD.
	INGNA6("INGNA6"), // APPL, SEZ
	INGNC6("INGNC6"), // GIFT SEZ LTD
	INGNG6("INGNG6"), // GIDC, SEZ
	INGNL6("INGNL6"), // LOMA ITPARK GHANSOLI
	INGNP6("INGNP6"), // GPRPL SEZ GURGAON
	INGNR6("INGNR6"), // LIPL/MARRIPLEMGUNTUR
	INGNT6("INGNT6"), // TCSL, SEZ
	INGOI4("INGOI4"), // Goa
	INGOP4("INGOP4"), // Gorakhpur
	INGPB6("INGPB6"), // PROGRESSIVE GURGAON
	INGPR1("INGPR1"), // Gopalpur
	INGRD6("INGRD6"), // Mumbai DP-II
	INGRL6("INGRL6"), // GPRL SEZ GURGAON
	INGRN6("INGRN6"), // RELIANCE SEZ GURGAON
	INGRR6("INGRR6"), // Mumbai DP-I
	INGRS6("INGRS6"), // RAHEJA SEZ GURGAON
	INGRW6("INGRW6"), // APM ICD BHAMBOLIKHED
	INGTGB("INGTGB"), // Gitaldah road
	INGTI6("INGTI6"), // INFOSYS TECH. LTD.
	INGTR2("INGTR2"), // Guntur
	INGTS6("INGTS6"), // SP PVT. LTD.
	INGTZB("INGTZB"), // Getandah
	INGUX4("INGUX4"), // Guna
	INGWL4("INGWL4"), // Gwalior
	INGWL6("INGWL6"), // Malanpuri (Gwalior)
	INGWM4("INGWM4"), // VIJAYAWADA AIRPORT
	INHAL1("INHAL1"), // Haldia
	INHAN6("INHAN6"), // HINDAUN ICD KARAULI
	INHAO6("INHAO6"), // OPTOINFRA/SEZ/HASSAN
	INHAS6("INHAS6"), // HASSAN ICD
	INHBB6("INHBB6"), // SDPL SEZ BENGALURU
	INHBX4("INHBX4"), // Hubli
	INHDD6("INHDD6"), // SIDCUL ICD PANTNAGAR
	INHEB6("INHEB6"), // GOCL SEZ BENGALURU
	INHEI6("INHEI6"), // INFOSYS/SEZ/MYSORE
	INHEM6("INHEM6"), // MEBP/SEZ/BANGALORE
	INHGLB("INHGLB"), // Hingalganj
	INHGT1("INHGT1"), // Hangarkatta
	INHIR6("INHIR6"), // SHB ICD SURAT
	INHJR4("INHJR4"), // Khajuraho
	INHLD2("INHLD2"), // Haldibari Railway St
	INHLE6("INHLE6"), // INFY SEZ BEGURHOBLI
	INHLIB("INHLIB"), // Hilli
	INHND1("INHND1"), // HEMNAGAR PORT
	INHON1("INHON1"), // Honavar
	INHPI6("INHPI6"), // SANDKHERA ICD KASHIP
	INHRN1("INHRN1"), // Harnai
	INHSF6("INHSF6"), // KIADBFP SEZ HASSAN
	INHSP6("INHSP6"), // KIADBP SEZ HASSAN
	INHSS4("INHSS4"), // Hissar
	INHST6("INHST6"), // KIADBT SEZ HASSAN
	INHSU6("INHSU6"), // ICD HOSUR
	INHTSB("INHTSB"), // Hatisar
	INHUR6("INHUR6"), // M/S RASSI, SEZ
	INHWR1("INHWR1"), // Honawar
	INHYB6("INHYB6"), // LHT PARK PVT. LTD.
	INHYD4("INHYD4"), // Hyderabad
	INHYD5("INHYD5"), // FPO HYDERABAD
	INHYD6("INHYD6"), // Hyderabad
	INHZA1("INHZA1"), // HAZIRA, SURAT
	INHZA6("INHZA6"), // Hazira SEZ, Surat
	INIDR4("INIDR4"), // Indore
	INIDR6("INIDR6"), // Indore(EPZ/SEZ)
	INIGU6("INIGU6"), // Coimbatore Irugur IC
	INILP6("INILP6"), // Tiruvallur-ILP ICD
	INIMF4("INIMF4"), // Imphal
	ININB6("ININB6"), // CRYSTAL IT PARK, SEZ
	ININD6("ININD6"), // ICD Pithampur
	ININI6("ININI6"), // IMPETUS INFOTECH SEZ
	ININN6("ININN6"), // INFOSYS SEZ INDORE
	ININT6("ININT6"), // TCS SEZ INDORE
	INISK4("INISK4"), // Nasik
	INISK6("INISK6"), // Nasik
	INIXA4("INIXA4"), // Agartala
	INIXB4("INIXB4"), // Bagdogra
	INIXC4("INIXC4"), // Chandigarh
	INIXD4("INIXD4"), // Allahabad
	INIXE1("INIXE1"), // Mangalore
	INIXE4("INIXE4"), // Mangalore
	INIXG4("INIXG4"), // Belgaum
	INIXH4("INIXH4"), // Kailashahar
	INIXI4("INIXI4"), // Lilabari
	INIXJ4("INIXJ4"), // Jammu
	INIXK4("INIXK4"), // Keshod
	INIXL4("INIXL4"), // Leh
	INIXL5("INIXL5"), // FPO LEH
	INIXM4("INIXM4"), // Madurai
	INIXM6("INIXM6"), // MaduraiICD
	INIXN4("INIXN4"), // Khowai
	INIXP4("INIXP4"), // Pathankot
	INIXQ4("INIXQ4"), // Kamalpur
	INIXR4("INIXR4"), // Ranchi
	INIXS4("INIXS4"), // Silchar
	INIXT4("INIXT4"), // Pasighat
	INIXU4("INIXU4"), // AURANGABAD
	INIXW4("INIXW4"), // Jamshedpur
	INIXW6("INIXW6"), // Jamshedpur ICD
	INIXY1("INIXY1"), // Kandla
	INIXY4("INIXY4"), // Kandla
	INIXY6("INIXY6"), // Kandla SEZ
	INIXZ1("INIXZ1"), // Port Blair
	INIXZ4("INIXZ4"), // Port Blair
	INJAI4("INJAI4"), // Jaipur
	INJAI5("INJAI5"), // Jaipur
	INJAI6("INJAI6"), // Jaipur
	INJAK1("INJAK1"), // Jakhau
	INJAL6("INJAL6"), // Jalgaon
	INJAYB("INJAYB"), // Jayanagar
	INJBD1("INJBD1"), // Jafrabad
	INJBL6("INJBL6"), // E-COMPLEX SEZ/Amreli
	INJBNB("INJBNB"), // JOGBANI
	INJDA1("INJDA1"), // Jodia
	INJDH4("INJDH4"), // Jodhpur
	INJDH6("INJDH6"), // Jodhpur
	INJGA4("INJGA4"), // Jamnagar
	INJGB4("INJGB4"), // Jagdalpur
	INJGD1("INJGD1"), // Jaigad
	INJGI6("INJGI6"), // GENPACT SEZ JAIPUR
	INJHA6("INJHA6"), // VEDANTA ALU. LTD.
	INJHOB("INJHOB"), // Jhulaghat (Pithoraga
	INJHV6("INJHV6"), // VEDANTASEZJHARSUGUDA
	INJIGB("INJIGB"), // Jaigaon
	INJJK6("INJJK6"), // ICD JSL JAJPUR
	INJKA6("INJKA6"), // SACHANA ICD VIRAMGAM
	INJLR4("INJLR4"), // Jabalpur
	INJNJ6("INJNJ6"), // NEWFOUND SEZ THANE
	INJNR4("INJNR4"), // Nashik-Janori ACC
	INJNR6("INJNR6"), // Nashik-Janori ICD
	INJPGB("INJPGB"), // Jalpaiguri
	INJPI6("INJPI6"), // RIICO SEZ 1 SITAPUR
	INJPV6("INJPV6"), // VATIKA SEZ JAIPUR
	INJPW6("INJPW6"), // MWC JAIPUR LTD.
	INJRH4("INJRH4"), // Jorhat
	INJSA4("INJSA4"), // Jaisalmer
	INJSG6("INJSG6"), // CONCOR JHARSUGUDA
	INJSM6("INJSM6"), // ADANI POWER SEZ
	INJSZ6("INJSZ6"), // JAIPUR SEZ
	INJTP1("INJTP1"), // Jaitapur
	INJUC6("INJUC6"), // Jalandhar
	INJUX6("INJUX6"), // Basni Jodhpur ICD
	INJWAB("INJWAB"), // Jarwa
	INKAK1("INKAK1"), // Kakinada
	INKAK6("INKAK6"), // Kakinada
	INKAL1("INKAL1"), // Kallai
	INKAP6("INKAP6"), // Kapadra (Surat)
	INKAR6("INKAR6"), // Karur ICD
	INKAT1("INKAT1"), // KATTUPALLI PORT
	INKBC6("INKBC6"), // ICD HAZIRA
	INKBT1("INKBT1"), // Khambhat
	INKCG6("INKCG6"), // NSL SEZ PVT. LTD.
	INKDD6("INKDD6"), // Karedu
	INKDI1("INKDI1"), // Kadmat Island
	INKDL6("INKDL6"), // KANDLA SEZ
	INKDN1("INKDN1"), // Kodinar(Muldwarka)
	INKDP1("INKDP1"), // Kondiapetnam
	INKELB("INKELB"), // Kel Sahar Subdivisio
	INKGG6("INKGG6"), // GLOBAL/SEZ/BANGALORE
	INKGJ1("INKGJ1"), // KARIMGANJ STEAMERGHA
	INKHD6("INKHD6"), // ICD Kheda-Dhar
	INKIW1("INKIW1"), // Kelwa
	INKJA6("INKJA6"), // APP/SEZ/DODAKANAHALI
	INKJB6("INKJB6"), // BAGMAN/SEZ/BANGALORE
	INKJD6("INKJD6"), // DIVYA/SEZ/BANGALORE
	INKJG6("INKJG6"), // GOPALAN/SEZ/BANGALOR
	INKJH6("INKJH6"), // HCL/SEZ/BANGALORE
	INKJIB("INKJIB"), // PIPRAUN LCS
	INKJM6("INKJM6"), // BD SEZ BENGALURU
	INKJR6("INKJR6"), // BBREL KUNDALAHALLI
	INKKR1("INKKR1"), // Kilakari
	INKKU6("INKKU6"), // Kanakpura Jaipur ICD
	INKLB6("INKLB6"), // BLUE/SEZ/ERNAKULAM
	INKLC6("INKLC6"), // CARB/SEZ/ERNAKULAM
	INKLG6("INKLG6"), // SGS/SEZ/ERNAKULAM
	INKLH4("INKLH4"), // Kohlapur
	INKLI6("INKLI6"), // INFOPARK/SEZ/EKM
	INKLK6("INKLK6"), // KINFRA KANAYANNOOR
	INKLM6("INKLM6"), // MULTISERVCEKALAMBOLI
	INKLN6("INKLN6"), // IT/ITES/SEZ/KALAMBOL
	INKLS6("INKLS6"), // SMART CITY SEZ KOCHI
	INKLY1("INKLY1"), // Kalyan
	INKMAB("INKMAB"), // KULKULI LCS
	INKMB1("INKMB1"), // Kumbharu
	INKMI6("INKMI6"), // INFO SEZ ERNAKULAM
	INKML6("INKML6"), // DEIPL KURUBARAPALLI
	INKND1("INKND1"), // Kankudy
	INKNK6("INKNK6"), // INFOPARK SEZ KORATTY
	INKNLB("INKNLB"), // Kunauli
	INKNU4("INKNU4"), // Kanpur
	INKNU5("INKNU5"), // FPO KANPUR
	INKNU6("INKNU6"), // Kanpur
	INKOC5("INKOC5"), // Kochi
	INKOD1("INKOD1"), // Kodinar
	INKOI1("INKOI1"), // Koilthottum
	INKOK1("INKOK1"), // Koka
	INKON1("INKON1"), // Konarak
	INKPK6("INKPK6"), // CONCOR ICD MIHAN
	INKRI1("INKRI1"), // Krishnapatnam
	INKRK1("INKRK1"), // Karaikal
	INKRM6("INKRM6"), // MADC LTD.
	INKRN1("INKRN1"), // Karanja
	INKRP1("INKRP1"), // Kiranpani
	INKRW1("INKRW1"), // Karwar
	INKSG1("INKSG1"), // Kasargod
	INKSH1("INKSH1"), // Kelshi
	INKSP1("INKSP1"), // Kulasekarapatnam
	INKTD1("INKTD1"), // Kotda
	INKTGB("INKTGB"), // Katarniyaghat
	INKTI1("INKTI1"), // Kiltan Island
	INKTRB("INKTRB"), // Kathihar
	INKTT6("INKTT6"), // Kota
	INKTU4("INKTU4"), // Kota
	INKTU6("INKTU6"), // Kota
	INKTW1("INKTW1"), // Koteshwar
	INKTY6("INKTY6"), // CHEYYAR POCHAMPALLI
	INKUK1("INKUK1"), // KOLLAM PORT
	INKUK6("INKUK6"), // KSITIL/SEZ/KOLLAM
	INKUR6("INKUR6"), // OIIDC SEZ KHURDA
	INKUU4("INKUU4"), // Kulu
	INKVI1("INKVI1"), // Kavi
	INKVL1("INKVL1"), // Kovalam
	INKVR6("INKVR6"), // WFPML SEZ KOVVUR
	INKVT1("INKVT1"), // Kavaratti Island
	INKWAB("INKWAB"), // Khunwa
	INKWGB("INKWGB"), // Khowaighat
	INKWHB("INKWHB"), // KAKRAHAWA LCS
	INKXJ2("INKXJ2"), // Karimganj Railway St
	INKYM6("INKYM6"), // KOTTAYAM
	INKZE6("INKZE6"), // E TECH-I/SEZ/THPURAM
	INKZP6("INKZP6"), // E PARK-III/SEZ/T'RAM
	INKZT6("INKZT6"), // E PARK-II/SEZ/TPURAM
	INLCH6("INLCH6"), // HCL IT SEZ LUCKNOW
	INLDA4("INLDA4"), // Malda
	INLDH6("INLDH6"), // Ludhiana
	INLGLB("INLGLB"), // Lalgola Town
	INLKO4("INLKO4"), // Lucknow
	INLKQB("INLKQB"), // LAUKAHA LCS
	INLON6("INLON6"), // ICD Loni
	INLPB6("INLPB6"), // BBLLP NANAKRAMGUDA
	INLPC6("INLPC6"), // CMC LTD.
	INLPD6("INLPD6"), // M/S DLF, SEZ
	INLPG6("INLPG6"), // GCPL SEZ KOKAPET
	INLPI6("INLPI6"), // M/S SUNDEW, SEZ
	INLPJ6("INLPJ6"), // RELIANCE SEZ
	INLPM6("INLPM6"), // MDL NANAKRAMGUDA
	INLPR1("INLPR1"), // Leapuram
	INLPS6("INLPS6"), // D NSL IP LTD.
	INLPW6("INLPW6"), // WIPRO LTD. HYDERABAD
	INLTBB("INLTBB"), // Latu Bazar
	INLUD6("INLUD6"), // LUDHIANA
	INLUH4("INLUH4"), // Ludhiana
	INLUH5("INLUH5"), // FPO LUDHIANA
	INLUH6("INLUH6"), // Ludhiana
	INLWG6("INLWG6"), // WIPRO LTD.
	INMAA1("INMAA1"), // Chennai (Ex Madras)
	INMAA4("INMAA4"), // Chennai (Ex Madras)
	INMAA5("INMAA5"), // Chennai (Ex Madras)
	INMAA6("INMAA6"), // Chennai(EPZ/SEZ)
	INMAB6("INMAB6"), // BRIGADE/SEZ/KANNADA
	INMAE6("INMAE6"), // EC OF TAMIL NADU
	INMAH1("INMAH1"), // Mahe
	INMAI6("INMAI6"), // INFOSYS/SEZ/MANGALOR
	INMAL1("INMAL1"), // Malpe
	INMAP1("INMAP1"), // Masulipatnam
	INMAQ6("INMAQ6"), // MANGALORE SEZ
	INMAS6("INMAS6"), // TRIL INFOPARK LTD.
	INMBC6("INMBC6"), // Moradabad(EPZ/SEZ)
	INMBD6("INMBD6"), // Pakwara (Moradabad)
	INMBS6("INMBS6"), // Madhosingh ICD
	INMCI1("INMCI1"), // Minicoi I
	INMDA1("INMDA1"), // Magdalla
	INMDD6("INMDD6"), // Mandideep ICD
	INMDE6("INMDE6"), // APIIC SEZ MEDAK
	INMDG6("INMDG6"), // Margao
	INMDK1("INMDK1"), // Muldwarka
	INMDP1("INMDP1"), // Mandapam
	INMDU6("INMDU6"), // KERN ICD MADURAI
	INMDV1("INMDV1"), // Mandvi
	INMDW1("INMDW1"), // Meadows
	INMEA6("INMEA6"), // APIIC-SEZ/ViII-LALGA
	INMEC6("INMEC6"), // EC OF TAMIL NADU
	INMGHB("INMGHB"), // Mahendraganj
	INMGR1("INMGR1"), // Mangrol
	INMHA1("INMHA1"), // Mahuva
	INMHDB("INMHDB"), // Kotawalighat (Mohedi
	INMHE1("INMHE1"), // Mahe
	INMHGB("INMHGB"), // Mahurighat
	INMHN2("INMHN2"), // Mahisashan Railway S
	INMKCB("INMKCB"), // Manikarchar
	INMKD6("INMKD6"), // MIKADO SEZ GURGAON
	INMLI1("INMLI1"), // Maroli
	INMLP1("INMLP1"), // Mallipuram
	INMLW1("INMLW1"), // Malwan
	INMNB2("INMNB2"), // Munabao Railway Stat
	INMNR1("INMNR1"), // Manori
	INMNUB("INMNUB"), // Manu
	INMNW1("INMNW1"), // Mandwa
	INMOH4("INMOH4"), // Mohanbari
	INMOR2("INMOR2"), // Moradabad
	INMPC1("INMPC1"), // TEST
	INMPR6("INMPR6"), // Malanpur ICD
	INMQK6("INMQK6"), // KIADB/SEZ/MANGALORE
	INMRA1("INMRA1"), // Mora
	INMRD1("INMRD1"), // Murad
	INMREB("INMREB"), // Moreh
	INMRG4("INMRG4"), // Margao
	INMRJ6("INMRJ6"), // Miraj
	INMRM1("INMRM1"), // Marmagoa
	INMSR6("INMSR6"), // RENAIS/SEZ/BANGALORE
	INMTW1("INMTW1"), // Metwad
	INMUC6("INMUC6"), // SCPL/SEZ/MULUND
	INMUL6("INMUL6"), // Mulund ICD
	INMUN1("INMUN1"), // Mundra
	INMUR1("INMUR1"), // Murad
	INMUZ6("INMUZ6"), // MODINAGAR ICD
	INMWA6("INMWA6"), // ICD Maliwada
	INMYB1("INMYB1"), // Mayabandar
	INMYL6("INMYL6"), // L AND T/SEZ/MYSORE
	INMYO6("INMYO6"), // OPTOINFRA/SEZ/MYSORE
	INMYQ4("INMYQ4"), // Mysore
	INMZA4("INMZA4"), // Muzaffarnagar
	INMZU4("INMZU4"), // Muzaffarpur
	INNAG4("INNAG4"), // Nagpur
	INNAG6("INNAG6"), // Nagpur
	INNAN1("INNAN1"), // Nancowrie
	INNAV1("INNAV1"), // Navlakhi
	INNDA6("INNDA6"), // Noida(EPZ/SEZ)
	INNDC4("INNDC4"), // Nanded
	INNDG1("INNDG1"), // Nandgaon
	INNDP1("INNDP1"), // Tuglakabad
	INNEE1("INNEE1"), // Neendakara
	INNEL1("INNEL1"), // Nellore
	INNGB6("INNGB6"), // BUTIBORI ICD NAGPUR
	INNGKB("INNGKB"), // NAGARKATA LCS
	INNGO6("INNGO6"), // OSE SEZ NOIDA
	INNGP6("INNGP6"), // Nagpur
	INNGRB("INNGRB"), // Nepalgunj Road
	INNGSB("INNGSB"), // Village Namgaya Ship
	INNKI6("INNKI6"), // INDIABULLS NASHIK
	INNKNB("INNKNB"), // Namkhana
	INNML1("INNML1"), // New Mangalore
	INNMTB("INNMTB"), // Neamati steamer Ghat
	INNNN6("INNNN6"), // AMRL SEZ NANGUNERI
	INNPGB("INNPGB"), // Nampong
	INNPT1("INNPT1"), // Nagapattinam
	INNRP6("INNRP6"), // AA LTD.
	INNSA1("INNSA1"), // Jawaharlal Nehru (Nh
	INNSK6("INNSK6"), // Nasik
	INNTLB("INNTLB"), // SHERATHANG LCS
	INNTVB("INNTVB"), // THOOTHIBARI LCS
	INNUR6("INNUR6"), // Kundli
	INNVB1("INNVB1"), // Navabunder(with its
	INNVP1("INNVP1"), // Navaspur
	INNVT1("INNVT1"), // Nivti
	INNVY4("INNVY4"), // Neyveli
	INNWP1("INNWP1"), // Newapur
	INNYP6("INNYP6"), // APIIC LTD.
	INOKH1("INOKH1"), // Okha
	INOMN4("INOMN4"), // Osmanabad
	INOMU1("INOMU1"), // Old Mundra Port
	INONJ1("INONJ1"), // Onjal
	INPAB4("INPAB4"), // Bilaspur
	INPAK6("INPAK6"), // KSITIL/SEZ/PAYYANOOR
	INPAN1("INPAN1"), // Panaji Port
	INPAO6("INPAO6"), // HBS SEZ PANOLI
	INPAP2("INPAP2"), // Panipat
	INPAT4("INPAT4"), // Patna
	INPAV1("INPAV1"), // Pipavav (Victor) Por
	INPAV2("INPAV2"), // Pipavav (Victor) Por
	INPBD1("INPBD1"), // Porbandar
	INPBD4("INPBD4"), // Porbandar
	INPBLB("INPBLB"), // KAMARDWISA LCS
	INPDD1("INPDD1"), // Padubidri Minor Port
	INPEK6("INPEK6"), // EKIPL/SEZ/PUNE
	INPGH4("INPGH4"), // Pantnagar
	INPHBB("INPHBB"), // Phulbari
	INPID1("INPID1"), // Port Indai
	INPIN1("INPIN1"), // Pindhara
	INPIT6("INPIT6"), // ITL/SEZ/PUNE
	INPKD6("INPKD6"), // IGEL SEZ SETTIPALI
	INPKR6("INPKR6"), // ICD PALI, REWARI
	INPMB1("INPMB1"), // Pamban
	INPMP6("INPMP6"), // Pimpri
	INPMT6("INPMT6"), // MTDCCL/SEZ/PUNE
	INPNB6("INPNB6"), // BTSL SEZ PUNE
	INPNE6("INPNE6"), // NT PVT. LTD.
	INPNF5("INPNF5"), // PATNA FPO
	INPNI6("INPNI6"), // MITTAL SEZ PANIPAT
	INPNJ1("INPNJ1"), // Panjim
	INPNK6("INPNK6"), // KLPPL PANKI
	INPNL6("INPNL6"), // PERSIPINA SEZ RAIGAD
	INPNM1("INPNM1"), // Panambur
	INPNN1("INPNN1"), // Ponnani
	INPNP6("INPNP6"), // Babarpur
	INPNQ2("INPNQ2"), // Pune
	INPNQ4("INPNQ4"), // Pune
	INPNQ6("INPNQ6"), // SERUM BIO/SEZ/PUNE
	INPNTB("INPNTB"), // Panitanki(Naxalbari)
	INPNU6("INPNU6"), // TMSF PVT. LTD.
	INPNV6("INPNV6"), // ICD Panvel
	INPNY1("INPNY1"), // Pondicherry
	INPNY4("INPNY4"), // Pondicherry
	INPNY6("INPNY6"), // ICD PULICHAPALLAM
	INPPG6("INPPG6"), // Patparganj ICD,DELHI
	INPPJ1("INPPJ1"), // Pellet Plant Jetty a
	INPRD6("INPRD6"), // PREPL SEZ PERUNGUDI
	INPRG1("INPRG1"), // Purangad
	INPRK6("INPRK6"), // ICD POWARKHEDA
	INPRT1("INPRT1"), // Paradeep
	INPSH1("INPSH1"), // Palshet
	INPSI6("INPSI6"), // SIPL/SEZ/PUNE
	INPSN6("INPSN6"), // PERFECT SEZ NOIDA
	INPSP6("INPSP6"), // NSPL SEZ HINJEWADI
	INPTL6("INPTL6"), // Patli ICD
	INPTN1("INPTN1"), // Portonovo
	INPTPB("INPTPB"), // Petrapole LCS
	INPUA6("INPUA6"), // AIGP SEZ WAGHOLI
	INPUE6("INPUE6"), // EON KHARADI SEZ
	INPUI6("INPUI6"), // KIPPLGDPLSEZ KHARADI
	INPUL1("INPUL1"), // Pulicat
	INPUM6("INPUM6"), // MIDC PUNE
	INPUN6("INPUN6"), // M/S KBTV PVT., PUNE
	INPUR1("INPUR1"), // Puri
	INPUT4("INPUT4"), // Puttaparthi
	INPVL6("INPVL6"), // Panvel ICD
	INPVS6("INPVS6"), // SNPIP SEZ TAMBARAM
	INPWL6("INPWL6"), // PALWAL ICD
	INPYB4("INPYB4"), // Jeypore
	INPYS6("INPYS6"), // SIPCOT SEZ ERODE
	INQRP6("INQRP6"), // ADANI ICD KILARAIPUR
	INQUI1("INQUI1"), // Quilon
	INRAI6("INRAI6"), // Raipur
	INRAJ4("INRAJ4"), // Rajkot
	INRAJ6("INRAJ6"), // Rajkot
	INRAM1("INRAM1"), // Rameshwaram
	INRDP2("INRDP2"), // Radhikapur Railway S
	INREA6("INREA6"), // Rewari
	INRED1("INRED1"), // Redi
	INREW4("INREW4"), // Rewa
	INRGBB("INRGBB"), // Old Raghna Bazar
	INRGH4("INRGH4"), // Balurghat
	INRGJ2("INRGJ2"), // RAIGANJ LCS RLY
	INRGT1("INRGT1"), // Ranghat Bay
	INRGUB("INRGUB"), // Ryngku
	INRJA4("INRJA4"), // Rajahmundry
	INRJI4("INRJI4"), // Rajouri
	INRJN6("INRJN6"), // LS PVT. LTD.
	INRJP1("INRJP1"), // Rajpara
	INRJR1("INRJR1"), // Rajpuri
	INRKG1("INRKG1"), // Rajakkamangalam
	INRMD4("INRMD4"), // Ramagundam
	INRML6("INRML6"), // CONCOR ICDNAYARAIPUR
	INRNC5("INRNC5"), // RANCHI FPO
	INRNG2("INRNG2"), // Ranaghat Railway Sta
	INRNR1("INRNR1"), // Ranpar
	INRPL6("INRPL6"), // Raddipalam
	INRPR4("INRPR4"), // Raipur
	INRPR6("INRPR6"), // Raipur
	INRPU5("INRPU5"), // RAIPUR FPO
	INRRI1("INRRI1"), // Raili
	INRRK4("INRRK4"), // Rourkela
	INRTC1("INRTC1"), // Ratnagiri
	INRTC4("INRTC4"), // Ratnagiri
	INRTM6("INRTM6"), // CONCOR ICD RATLAM
	INRUP4("INRUP4"), // Rupsi
	INRVD1("INRVD1"), // Revdanda
	INRWR1("INRWR1"), // Rameshwaram
	INRXLB("INRXLB"), // Raxaul
	INSABB("INSABB"), // Sabroom
	INSAC6("INSAC6"), // Sachin (Surat)
	INSAJ6("INSAJ6"), // NAVKAR ICD UMBERGAON
	INSAL1("INSAL1"), // Salaya
	INSAS6("INSAS6"), // INFOSYS SEZ MOHALI
	INSAU6("INSAU6"), // THAR DRY PORT
	INSBC6("INSBC6"), // BIOCON SEZ BANGALORE
	INSBH1("INSBH1"), // Sinbhour
	INSBI6("INSBI6"), // ICD Sabarmati
	INSBK6("INSBK6"), // KIADB/SEZ/BANGALORE
	INSBL6("INSBL6"), // INFOSYS/SEZ/BANGLORE
	INSBW6("INSBW6"), // WIPRO ELEC/SEZ/BLR
	INSBZ1("INSBZ1"), // SHELLA BAZAR
	INSCH6("INSCH6"), // SAP-SEZ SURAT
	INSGF6("INSGF6"), // GRFL ICD SAHNEWAL
	INSHI1("INSHI1"), // Shirola
	INSHL4("INSHL4"), // Shillong
	INSHP1("INSHP1"), // Sinbhour Port
	INSIK1("INSIK1"), // Sikka
	INSJR6("INSJR6"), // Surajpur
	INSKD6("INSKD6"), // ICD KALINGANAGAR
	INSKPB("INSKPB"), // Sukhia Pokhari
	INSLL6("INSLL6"), // Singanallur
	INSLR2("INSLR2"), // Silcher R.M.S. Offic
	INSLRB("INSLRB"), // Silcher Steamerghat
	INSLT6("INSLT6"), // SALT LAKE (EPZ/SEZ)
	INSLV4("INSLV4"), // Simla
	INSMK6("INSMK6"), // KEONICS/SEZ/SHIMOGA
	INSMPB("INSMPB"), // Srimantapur
	INSMR1("INSMR1"), // Simor
	INSNA6("INSNA6"), // ANSAL SEZ SONEPAT
	INSNBB("INSNBB"), // Sonabarsa
	INSNF6("INSNF6"), // ICD, Hyderabad
	INSNG2("INSNG2"), // Singabad Railway Sta
	INSNI6("INSNI6"), // KANECH, ICD SAHNEWAL
	INSNLB("INSNLB"), // Sonauli
	INSNN6("INSNN6"), // APIIC LTD.
	INSNR6("INSNR6"), // ARI LTD.
	INSNS6("INSNS6"), // NLE PVT. LTD.
	INSPC6("INSPC6"), // CCLPIL SEZ VIZAG
	INSPE6("INSPE6"), // ASDI SEZ NELLORE
	INSRE6("INSRE6"), // Saharanpur
	INSRK6("INSRK6"), // KSITILA/SEZ/PALI/ALZ
	INSRV1("INSRV1"), // Surasani-Yanam
	INSSE4("INSSE4"), // Sholapur
	INSTFB("INSTFB"), // SIKTA LCS
	INSTIB("INSTIB"), // Sitai
	INSTM6("INSTM6"), // MIDC PHALTAN SEZ
	INSTP1("INSTP1"), // Satpati
	INSTRB("INSTRB"), // Sutarkandi
	INSTT6("INSTT6"), // Dadri STTPL CFS
	INSTU6("INSTU6"), // MIDC SEZ SATARA
	INSTV1("INSTV1"), // Surat
	INSTV4("INSTV4"), // Surat
	INSTV6("INSTV6"), // Surat(EPZ/SEZ)
	INSWD1("INSWD1"), // Shriwardhan
	INSXE6("INSXE6"), // ELCOT AMMAPALAYAM
	INSXR4("INSXR4"), // Srinagar
	INSXR5("INSXR5"), // FPO SRINAGAR
	INSXV4("INSXV4"), // Salem
	INSXV6("INSXV6"), // Salem
	INTAD1("INTAD1"), // Tadri
	INTAS6("INTAS6"), // SRICITYPVTLTD-SEZ
	INTBC6("INTBC6"), // CTS PVT. LTD.
	INTBM6("INTBM6"), // PHPL SEZ KANCHEPURAM
	INTBP6("INTBP6"), // SPIPL SEZ, PERUGULTH
	INTBS6("INTBS6"), // HEXAWARE TECH. LTD.
	INTBT6("INTBT6"), // TCS LTD.
	INTCR6("INTCR6"), // M/S TICS, ICD MATHIL
	INTDE6("INTDE6"), // Tudiyalur-Coimbatore
	INTEI4("INTEI4"), // Tezu
	INTEL1("INTEL1"), // Tellicherry
	INTEN6("INTEN6"), // SIPCOT GANGAKONDAN
	INTEZ4("INTEZ4"), // Tezpur
	INTGN6("INTGN6"), // KEIPL/ PUNE
	INTHA6("INTHA6"), // Thar Dry Port Jodhpu
	INTHL1("INTHL1"), // Thal
	INTHO6("INTHO6"), // Tiruppur-Thottiplaya
	INTIR4("INTIR4"), // Tirupati
	INTIV1("INTIV1"), // Tiviri
	INTJA1("INTJA1"), // Talaja
	INTJPB("INTJPB"), // Tezpur Steamerghat
	INTJV4("INTJV4"), // Thanjavur
	INTKD2("INTKD2"), // Tuglakabad
	INTKD6("INTKD6"), // Tuglakabad
	INTKNB("INTKNB"), // Tikonia
	INTLG6("INTLG6"), // Pune-Talegoan ICD
	INTLT6("INTLT6"), // L&T SBL L&T CHENNAI
	INTMI6("INTMI6"), // M/S IFFCO KISAN, SEZ
	INTMP1("INTMP1"), // Trombay
	INTMX6("INTMX6"), // ICD, THIMMAPUR,
	INTNA1("INTNA1"), // Thana
	INTNC6("INTNC6"), // CCCL SEZ TUTICORIN
	INTND1("INTND1"), // Tondi
	INTNGB("INTNGB"), // Tungi
	INTNI6("INTNI6"), // HIPL SEZ
	INTNK1("INTNK1"), // Tankari
	INTNS6("INTNS6"), // SSL SEZ TUTICORIN
	INTPH1("INTPH1"), // Thopputhurai
	INTPJ6("INTPJ6"), // ECTN SEZ TRICHY
	INTPN1("INTPN1"), // Talpona
	INTRA1("INTRA1"), // Tranquebar
	INTRL6("INTRL6"), // ICD Tiruvallur
	INTRP1("INTRP1"), // Tarapur
	INTRV4("INTRV4"), // Thiruvananthapuram (
	INTRZ4("INTRZ4"), // Tiruchirapalli
	INTSI6("INTSI6"), // HVCPL SEZ KADAYAM
	INTTP6("INTTP6"), // Dadri TTPL
	INTTS1("INTTS1"), // T.T. SHED (KIDDERPOR
	INTUI6("INTUI6"), // FCPL SEZ KESAVARAM
	INTUN1("INTUN1"), // Tuna
	INTUP6("INTUP6"), // Tirupur
	INTUT1("INTUT1"), // Tuticorin
	INTUT6("INTUT6"), // Tuticorin ICD
	INTVC6("INTVC6"), // KINFRAA SEZ
	INTVT6("INTVT6"), // ICD TONDIARPET CHENN
	INTYR1("INTYR1"), // Tirukkadayyur
	INUDI6("INUDI6"), // SYNEFRA-SEZ/UDUPI
	INUDN6("INUDN6"), // GHB-SEZ SURAT
	INUDR4("INUDR4"), // Udaipur
	INUDR6("INUDR6"), // Udaipur
	INUDZ6("INUDZ6"), // Udaipur
	INUKL6("INUKL6"), // ETLISL SEZ ERODE
	INULPB("INULPB"), // Ultapani
	INULW1("INULW1"), // Ulwa
	INUMB1("INUMB1"), // Umbergoan
	INUMR1("INUMR1"), // Umarsadi
	INURF6("INURF6"), // FAB CITY SPV-SEZ/SRI
	INURG6("INURG6"), // GMR HYDTABAD AVIATIO
	INURI6("INURI6"), // INDU TECHZONE PVT.
	INURT6("INURT6"), // TCS LTD. ADIBATLA
	INUTN1("INUTN1"), // Uttan
	INVAD1("INVAD1"), // Vadinar
	INVAL6("INVAL6"), // Valvada ICD
	INVAP1("INVAP1"), // Vapi
	INVEN1("INVEN1"), // Vengurla
	INVEP1("INVEP1"), // Veppalodai
	INVGA4("INVGA4"), // Vijayawada
	INVGA5("INVGA5"), // FPO VIJAYAWADA
	INVGR6("INVGR6"), // BHOJVA ICD VIRAMGAM
	INVKH6("INVKH6"), // HIRANANDANI BUIL.
	INVKM1("INVKM1"), // Valinokkam
	INVLD6("INVLD6"), // DISH/SEZ/KALYANGADH
	INVLN6("INVLN6"), // NG REALTY-SEZ/TALUKA
	INVLR6("INVLR6"), // SIPCOT LTD.
	INVNG1("INVNG1"), // Vengurla
	INVNS4("INVNS4"), // Varanasi
	INVNS5("INVNS5"), // FPO VARANASI
	INVNS6("INVNS6"), // Varanasi
	INVPI6("INVPI6"), // Vapi
	INVRD1("INVRD1"), // Varavda
	INVRU1("INVRU1"), // Vadarevu
	INVSA6("INVSA6"), // APIIC (HALL NO.3)
	INVSI1("INVSI1"), // Vansi-Borsi
	INVSK6("INVSK6"), // APIIC- (HALL NO. 2)
	INVSP6("INVSP6"), // WIPRO SEZRESPUVANIPA
	INVSV1("INVSV1"), // Varsova
	INVTC6("INVTC6"), // CHEYYAR VELLORE
	INVTZ1("INVTZ1"), // Visakhapatnam
	INVTZ4("INVTZ4"), // Visakhapatnam
	INVTZ6("INVTZ6"), // Visakhapatnam SEZ
	INVVA1("INVVA1"), // Veraval
	INVYD1("INVYD1"), // Vijaydurg
	INVZJ1("INVZJ1"), // Vazhinjam
	INVZM6("INVZM6"), // DLL SEZ
	INVZR6("INVZR6"), // M/S DR. REDDY SEZ
	INWAL6("INWAL6"), // Waluj (Aurangabad)
	INWFD6("INWFD6"), // ICD Bangalore
	INWFI6("INWFI6"), // INFO/SEZ/BANGALORE
	INWFT6("INWFT6"), // ITPL SEZ II BENGALUR
	INWGC4("INWGC4"), // Warrangal
	INWRR6("INWRR6"), // WARDHA POWER CO LTD
	INYMA6("INYMA6"), // MODERN ASSET SEZ II
	INYNA6("INYNA6"), // MOSERN ASSET SEZ I
	INYNK6("INYNK6"), // KIP/SEZ/N BANGALORE
	INYNL6("INYNL6"), // L&T CEL SEZ II
	INYNM6("INYNM6"), // MILESTONE/SEZ/BLR
	INYNT6("INYNT6"), // L&T CEL SEZ I
	INZIP6("INZIP6"); // ZIPL-SEZ AHMEDABA

	private String text;

	@JsonCreator
	@NotBlank
	@Length(max = 2, min = 10, message = "Port in Export Details should be https://docs.cleartax.in/cleartax-docs/e-invoicing-api/e-invoicing-api-reference/resources-and-master/port-code-master")
	private PortCode(String text) {
		this.text = text;
	}

	@JsonValue
	public String getText() {
		return this.text;
	}

	public static Optional<PortCode> fromText(String text) {
		return Arrays.stream(values()).filter(bl -> bl.text.equalsIgnoreCase(text)).findFirst();
	}

}
